name: Trigger auto deployment for container-app-lrf4nbn5ew4am

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-lrf4nbn5ew4am-AutoDeployTrigger-9c63d56f-b2c4-4ba8-98df-8ecfedd1a266.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPLRF4NBN5EW4AM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPLRF4NBN5EW4AM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPLRF4NBN5EW4AM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPLRF4NBN5EW4AM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPLRF4NBN5EW4AM_REGISTRY_PASSWORD }}
          containerAppName: container-app-lrf4nbn5ew4am
          resourceGroup: todonodejspgsqlgoogleauthb34ea998
          imageToBuild: default/container-app-lrf4nbn5ew4am:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


